app:
  type: dev
jwt:
  secret: Gpc8ZlCgJpA0hDAmuE70OAWjUNRbU0Ly2yxRFLne
postgres:
  host: localhost
  port: 5432
  user: postgres
  pass: postgres
  pool: 10
  db: arm
rest:
  listen_host: localhost
  listen_port: 8517
log:
  file_name: arms-rest.log
  path: .log
